CURRENT_SHELL="zsh"
SHELL_FILES="${$(readlink $HOME/.zshrc):h}"
DOT_FILES="${SHELL_FILES:h:h}"

source $DOT_FILES/shells/bootstrap.sh

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby ruby 2.0

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
