CURRENT_SHELL="zsh"
SHELL_FILES="${$(readlink $HOME/.zshrc):h}"
DOT_FILES="${SHELL_FILES:h:h}"

source $DOT_FILES/shells/bootstrap.sh

eval "$(rbenv init -)"

### Add the current directory's bin to PATH
export PATH="./bin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### path for android
export PATH=${PATH}:~/android-sdk-mac/tools

function import_heroku() {
  bundle exec rake db:drop db:create;
  echo $(source .env.development &&
    heroku pg:backups capture --app $1 &&
    curl -o db.dump `heroku pg:backups public-url --app $1` &&
    pg_restore -c -d $DATABASE db.dump
  );
  bundle exec rake db:migrate;
}

function add_pr_remotes() {
  mv .git/config .git/config-orig
  awk '/remote "origin"/  {
    print $0
    getline;
    print $0
    getline;
    print $0
    print "\tfetch = +refs/pull/*/head:refs/remotes/origin/pr/*"
  }1' .git/config-orig > .git/config
  git fetch origin
}
