CURRENT_SHELL="zsh"

DOT_FILES="${$(readlink $HOME/.zshrc):h:h:h:h}"

CONFIG_FILES="${DOT_FILES}/config"
SHELL_FILES="${CONFIG_FILES}/shells"
ZSH_SHELL_FILES="${SHELL_FILES}/zsh"
COMMON_SHELL_FILES="${SHELL_FILES}/common"

source $SHELL_FILES/bootstrap.sh

### add homebrew to PATH
export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH

### Add the current directory's bin to PATH
export PATH="./bin:$PATH"

export GPG_TTY=$(tty)

export KUBECONFIG=~/.kube/config
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

[[ -f "$HOME/.devenvrc" ]] && source $HOME/.devenvrc # add devenv-specific rc here
[[ -f "$HOME/.sproucrc" ]] && source $HOME/.sproutrc # add sprout-specific rc here
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

__git_files () { 
    _wanted files expl 'local files' _files     
}

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
